/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import java.io.File
import java.io.BufferedReader
import java.io.InputStreamReader

//import kotlinx.coroutines.*

class TestCsv {
    
    
    // menggunakan coroutines malah lambat
    /*
    suspend fun readCsvAndCalculateAsync(fileName: String): Double = withContext(Dispatchers.IO) {
        val file = File(fileName)
        val reader = BufferedReader(InputStreamReader(file.inputStream()))

        // Melewati baris pertama (header)
        reader.readLine() // Skip header

        var totalKoefisien = 0.0

        // Loop untuk membaca baris CSV dan menghitung koefisien
        reader.forEachLine { line ->
            val columns = line.split(",") // Pisahkan data berdasarkan koma
            val value1 = columns[0].toDouble()
            val value2 = columns[1].toDouble()
            val value3 = columns[2].toDouble()

            // Hitung koefisien
            totalKoefisien += calculateKoefisien(value1, value2, value3)
        }

        reader.close() // Tutup reader setelah selesai
        totalKoefisien // Kembalikan nilai total koefisien
    }

    fun calculateKoefisien(value1: Double, value2: Double, value3: Double): Double {
        // Contoh perhitungan koefisien
        return value1 * Math.cos(Math.toRadians(value2 + value3 * 3.5))
    }
    */

    
    // Fungsi untuk menghitung koefisien (contoh sederhana)
    fun calculateKoefisien(value1: Double, value2: Double, value3: Double): Double {
    // Contoh rumus koefisien (sesuaikan dengan kebutuhan)
        return value1 * Math.cos(Math.toRadians(value2 + value3 * 3.5))
    }

    // Fungsi untuk membaca CSV dan memproses data (tanpa header)
    fun readCsvAndCalculate(fileName: String): Double {
        val file = File(fileName)
        val reader = BufferedReader(InputStreamReader(file.inputStream()))
        

        // Melewati baris pertama (header)
        reader.readLine() // Skip header
        var koefisien = 0.0

        // Loop untuk membaca baris CSV dan menghitung koefisien
        reader.forEachLine { line ->
            val columns = line.split(",") // Pisahkan data berdasarkan koma
            val value1 = columns[1].toDouble() // index dimulai dr 0 (no term), jadi ambil data index ke 1
            val value2 = columns[2].toDouble()
            val value3 = columns[3].toDouble()
            

            // Hitung koefisien
            koefisien += calculateKoefisien(value1, value2, value3)
            
        }
        
        //println("Koefisien: $koefisien")
        reader.close() // Tutup reader setelah selesai
        return koefisien
    }

    
}
