/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertTrue
import org.example.TestCsv
import kotlinx.coroutines.runBlocking

class LibraryTest {

    
    @Test
    fun testCsv() {
        // Membaca data dari file CSV dan menghitung koefisien
        val koefisien = TestCsv().readCsvAndCalculate("src/main/resources/data.csv")
        
        println("jumlah total koefisien: $koefisien")
    
    }
    /*
    @Test
    fun csvCoroutines() = runBlocking {
        val fileName = "src/main/resources/data.csv"
    
        // Menjalankan pembacaan file secara asynchronous
        val totalKoefisien = TestCsv().readCsvAndCalculateAsync(fileName)
    
        println("Total Koefisien: $totalKoefisien")
    }
    */
}
